const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const loader=$('#loader'); setTimeout(()=>loader.classList.add('hide'),1900);
const nav=$('#nav'), menu=$('#menu'), mobile=$('#mobileMenu');
menu.addEventListener('click',()=>mobile.classList.toggle('open')); $$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>40),{passive:true});
const cursor=$('#cursor'); addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}); $$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('big'));el.addEventListener('mouseleave',()=>cursor.classList.remove('big'))});
const flash=$('#flash'); let lastScene=-1;
function pulse(){flash.animate([{opacity:0},{opacity:.18},{opacity:0}],{duration:360,easing:'cubic-bezier(.2,.8,.2,1)'})}
const scenes=$$('.v-scene');
const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('active'); const i=scenes.indexOf(en.target); if(i!==lastScene){lastScene=i;pulse()}}}),{threshold:.42}); scenes.forEach(s=>io.observe(s));
$$('.v-content,.studio-head,.person-card,.reel-copy,.contact-inner,.manifesto-word').forEach(el=>el.classList.add('reveal'));
const rev=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12}); $$('.reveal').forEach(e=>rev.observe(e));

// Lightweight dependency-free 3D renderer. It is intentionally self-contained for Cloudflare Pages.
class Space3D{
 constructor(canvas){this.c=canvas;this.x=canvas.getContext('2d');this.w=1;this.h=1;this.t=0;this.mode='camera';this.mx=0;this.my=0;this.resize();addEventListener('resize',()=>this.resize());addEventListener('pointermove',e=>{this.mx=(e.clientX/innerWidth-.5);this.my=(e.clientY/innerHeight-.5)});this.loop()}
 resize(){const d=Math.min(devicePixelRatio,2);this.w=this.c.clientWidth||innerWidth;this.h=this.c.clientHeight||innerHeight;this.c.width=this.w*d;this.c.height=this.h*d;this.x.setTransform(d,0,0,d,0,0)}
 proj(p,rx,ry,rz,scale){let [x,y,z]=p,cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx),cz=Math.cos(rz),sz=Math.sin(rz);let X=x*cy-z*sy,Z=x*sy+z*cy;let Y=y*cx-Z*sx;Z=y*sx+Z*cx;let X2=X*cz-Y*sz,Y2=X*sz+Y*cz;let f=scale/(scale+Z);return [this.w*.58+X2*f,this.h*.52+Y2*f,f]}
 line(a,b,style,w,rx,ry,rz,s){const A=this.proj(a,rx,ry,rz,s),B=this.proj(b,rx,ry,rz,s);this.x.strokeStyle=style;this.x.lineWidth=w;this.x.beginPath();this.x.moveTo(A[0],A[1]);this.x.lineTo(B[0],B[1]);this.x.stroke()}
 box(size,depth,rx,ry,rz,s,fill,wire=true){const q=size/2,d=depth/2;const V=[[-q,-q,-d],[q,-q,-d],[q,q,-d],[-q,q,-d],[-q,-q,d],[q,-q,d],[q,q,d],[-q,q,d]],E=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];if(fill){const P=V.map(v=>this.proj(v,rx,ry,rz,s));this.x.fillStyle=fill;this.x.beginPath();[0,1,2,3].forEach((i,k)=>k?this.x.lineTo(P[i][0],P[i][1]):this.x.moveTo(P[i][0],P[i][1]));this.x.closePath();this.x.fill()}E.forEach(e=>this.line(V[e[0]],V[e[1]],wire?'rgba(239,208,160,.48)':'rgba(0,0,0,0)',1.3,rx,ry,rz,s))}
 circle(r,rx,ry,rz,s,stroke='rgba(239,208,160,.6)',dash=0){this.x.strokeStyle=stroke;this.x.lineWidth=1;this.x.setLineDash(dash?[5,8]:[]);this.x.beginPath();this.x.ellipse(this.w*.58,this.h*.52,r*s*.72,r*s*.34,ry+rz,0,Math.PI*2);this.x.stroke();this.x.setLineDash([])}
 camera(){const rx=.08+this.my*.2,ry=this.t*.2+this.mx*.5,s=230;this.box(180,90,rx,ry,0,s,'rgba(12,10,9,.92)');this.box(70,55,rx,ry,0,s,'rgba(239,208,160,.08)');this.x.fillStyle='rgba(239,208,160,.9)';this.x.beginPath();this.x.ellipse(this.w*.58,this.h*.52,42,42,0,0,Math.PI*2);this.x.fill();this.x.fillStyle='#0b0908';this.x.beginPath();this.x.ellipse(this.w*.58,this.h*.52,25,25,0,0,Math.PI*2);this.x.fill();this.line([-80,60,0],[80,60,0],'rgba(239,208,160,.45)',4,rx,ry,0,s);this.line([-45,50,0],[-75,145,30],'rgba(239,208,160,.35)',3,rx,ry,0,s);this.line([45,50,0],[75,145,30],'rgba(239,208,160,.35)',3,rx,ry,0,s);this.circle(300,rx,ry,0,s);this.circle(420,rx,ry,0,s,'rgba(239,208,160,.15)')}
 vertical(mode){const rx=.25+this.my*.15,ry=this.t*.15+this.mx*.4,s=240; if(mode==='building'){for(let z=-70;z<=70;z+=35)this.box(170,32,rx,ry,0,s,null);this.x.fillStyle='rgba(239,208,160,.08)';for(let i=0;i<5;i++){let p=this.proj([-45+i*22,-15,-80],rx,ry,0,s);this.x.fillRect(p[0],p[1],12,18)}} if(mode==='product'){this.box(150,150,rx,ry,0,s,'rgba(239,208,160,.08)');for(let i=-2;i<=2;i++)this.line([i*22,-55,76],[i*22,55,76],'rgba(239,208,160,.32)',1,rx,ry,0,s)} if(mode==='plate'){this.circle(230,rx,ry,0,s,'rgba(239,208,160,.6)');this.circle(165,rx,ry,0,s,'rgba(239,208,160,.35)');this.x.fillStyle='rgba(239,208,160,.12)';this.x.beginPath();this.x.ellipse(this.w*.58,this.h*.52,70,28,0,0,Math.PI*2);this.x.fill()} if(mode==='person'){this.x.strokeStyle='rgba(239,208,160,.48)';this.x.lineWidth=2;this.x.beginPath();this.x.arc(this.w*.58,this.h*.44,55,0,Math.PI*2);this.x.stroke();this.line([-55,25,0],[-95,130,0],'rgba(239,208,160,.38)',4,rx,ry,0,s);this.line([55,25,0],[95,130,0],'rgba(239,208,160,.38)',4,rx,ry,0,s)} if(mode==='laptop'){this.box(180,25,rx,ry,0,s,'rgba(239,208,160,.08)');this.line([-105,70,0],[105,70,0],'rgba(239,208,160,.65)',3,rx,ry,0,s);this.line([-105,70,0],[-60,105,0],'rgba(239,208,160,.5)',2,rx,ry,0,s);this.line([105,70,0],[60,105,0],'rgba(239,208,160,.5)',2,rx,ry,0,s)} if(mode==='rings'){this.circle(170,rx,ry,0,s,'rgba(239,208,160,.9)');this.circle(120,rx+.25,ry+.2,.2,s,'rgba(255,250,241,.7)');this.circle(260,rx,ry,0,s,'rgba(239,208,160,.14)')} }
 loop(){this.t+=.006;this.x.clearRect(0,0,this.w,this.h);this.x.fillStyle='rgba(11,9,8,.12)';this.x.fillRect(0,0,this.w,this.h);if(this.mode==='camera')this.camera();else this.vertical(this.mode);requestAnimationFrame(()=>this.loop())}
}
const hero=new Space3D($('#heroCanvas'));
const map=['building','product','plate','person','laptop','rings'];function syncMode(){let active=scenes.find(s=>s.classList.contains('active'));hero.mode=active?map[scenes.indexOf(active)]:'camera'}setInterval(syncMode,120);
// Reel canvas: animated light field / film grain.
const rc=$('#reelCanvas'),ctx=rc.getContext('2d');let dots=[];function rr(){const d=Math.min(devicePixelRatio,2);rc.width=rc.clientWidth*d;rc.height=rc.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:70},()=>({x:Math.random()*rc.clientWidth,y:Math.random()*rc.clientHeight,z:Math.random()*1+.2,a:Math.random()*6.28}))}rr();addEventListener('resize',rr);function reel(){ctx.clearRect(0,0,rc.clientWidth,rc.clientHeight);const w=rc.clientWidth,h=rc.clientHeight;for(const p of dots){p.a+=.01*p.z;p.x+=Math.sin(p.a)*.25*p.z;p.y-=.3*p.z;if(p.y<-20)p.y=h+20;const r=1+p.z*5;ctx.strokeStyle=`rgba(239,208,160,${.08+.25*p.z})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke()}requestAnimationFrame(reel)}reel();
// keyboard accessibility
addEventListener('keydown',e=>{if(e.key==='Escape')mobile.classList.remove('open')});
